export const GET_TASK_LIST = 'GET_TASK_LIST'
export const ADDPRODUCT = 'ADDPRODUCT'
export const UPDATEPRODUCT = 'UPDATEPRODUCT'
export const DETAILPRODUCT = 'DETAILPRODUCT'

export const ADDUSER = 'ADDUSER'
export const UPDATEUSER = 'UPDATEUSER'
export const DETAILUSER = 'DETAILUSER'